/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pousada;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Secundário
 */
public class ConsultarReserva1 extends javax.swing.JFrame {
    Integer compara = 1;
    /**
     * Creates new form ConsultarReserva
     */
    public ConsultarReserva1() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("logo-mobile.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url); 
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtDataCheckOut = new javax.swing.JFormattedTextField();
        txtAc2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNome = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAc3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        in = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        cbNq = new javax.swing.JComboBox<>();
        txtDataCheckIn = new javax.swing.JFormattedTextField();
        cbMt = new javax.swing.JComboBox<>();
        txtCarro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rbDinheiro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCli = new javax.swing.JTable();
        rbCartaoDebito = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rbTransfBanc = new javax.swing.JRadioButton();
        txtAc1 = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lTexto = new javax.swing.JLabel();
        txtReserva = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDeposito = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        cbCp = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAc4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMv = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Reserva");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtDataCheckOut.setEditable(false);
        txtDataCheckOut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        txtAc2.setEditable(false);
        txtAc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAc2ActionPerformed(evt);
            }
        });

        txtNome.setEnabled(false);
        jScrollPane2.setViewportView(txtNome);

        jLabel19.setText("Como conhceu a pousada?");

        jLabel25.setText("Acompanhante 3:");

        jLabel21.setText("Depósito realizado");

        txtAc3.setEditable(false);
        txtAc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAc3ActionPerformed(evt);
            }
        });

        jLabel22.setText("Pagamento Check in");

        jLabel14.setText("Motivo da Viagem");

        in.setEditable(false);
        jScrollPane15.setViewportView(in);

        jLabel15.setText("Meio de transporte");

        cbNq.setFocusCycleRoot(true);
        cbNq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNqActionPerformed(evt);
            }
        });

        txtDataCheckIn.setEditable(false);
        txtDataCheckIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        cbMt.setFocusCycleRoot(true);
        cbMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMtActionPerformed(evt);
            }
        });

        txtCarro.setEditable(false);

        jLabel26.setText("Acompanhante 4:");

        rbDinheiro.setText("Dinheiro");
        rbDinheiro.setEnabled(false);

        tabCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Data de Check-in", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabCli);
        if (tabCli.getColumnModel().getColumnCount() > 0) {
            tabCli.getColumnModel().getColumn(0).setResizable(false);
            tabCli.getColumnModel().getColumn(1).setResizable(false);
            tabCli.getColumnModel().getColumn(2).setResizable(false);
            tabCli.getColumnModel().getColumn(3).setResizable(false);
        }

        rbCartaoDebito.setText("Cartão de Débito");
        rbCartaoDebito.setEnabled(false);

        jLabel23.setText("Acompanhante 1:");

        rbTransfBanc.setText("Transferencia Bancária");
        rbTransfBanc.setEnabled(false);

        txtAc1.setEditable(false);
        txtAc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAc1ActionPerformed(evt);
            }
        });

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyTyped(evt);
            }
        });

        jLabel16.setText("Placa do carro");

        lTexto.setText("Digite o nome do hóspede: ");

        txtReserva.setEditable(false);

        jLabel17.setText("Data Check in");

        txtDeposito.setEditable(false);
        txtDeposito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepositoFocusLost(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("CPF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Data Check out");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Nome");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel24.setText("Acompanhante 2:");

        cbCp.setFocusCycleRoot(true);
        cbCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCpActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        txtAc4.setEditable(false);
        txtAc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAc4ActionPerformed(evt);
            }
        });

        jLabel20.setText("Valor da reserva");

        jLabel3.setText("Nº Quarto");

        cbMv.setFocusCycleRoot(true);
        cbMv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMvActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Check-in");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(682, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lTexto)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel15)
                            .addGap(49, 49, 49)
                            .addComponent(jLabel19))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(cbMv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(cbMt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(cbCp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel17)
                            .addGap(54, 54, 54)
                            .addComponent(jLabel18)
                            .addGap(36, 36, 36)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(txtDataCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(txtDataCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(cbNq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel20)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel21))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(txtReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jLabel16))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(383, 383, 383)
                            .addComponent(txtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel23)
                            .addGap(5, 5, 5)
                            .addComponent(txtAc1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26))
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAc2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAc3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAc4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbTransfBanc)
                                .addComponent(rbCartaoDebito)
                                .addComponent(rbDinheiro))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lTexto)
                            .addGap(6, 6, 6)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel2)
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel19))))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbMv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbNq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel16)))
                            .addGap(6, 6, 6)
                            .addComponent(txtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(txtAc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(6, 6, 6)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(rbTransfBanc))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(rbCartaoDebito))
                                        .addComponent(rbDinheiro)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(16, 16, 16)
                                            .addComponent(jLabel25)
                                            .addGap(16, 16, 16)
                                            .addComponent(jLabel26))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtAc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txtAc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txtAc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAc2ActionPerformed

    private void txtAc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAc3ActionPerformed

    private void cbNqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNqActionPerformed

    private void cbMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMtActionPerformed

    private void tabCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCliMouseClicked
        String codigo = tabCli.getValueAt(tabCli.getSelectedRow(), 0).toString();
        System.out.println("código cliente: "+codigo);
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";

            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = conexao.prepareStatement("Select reserva.cod_quarto, DATE_FORMAT(reserva.check_in, \"%d/%m/%Y\") as check_in, DATE_FORMAT(reserva.check_out, \"%d/%m/%Y\") as check_out, reserva.placa_carro, reserva.reserva, reserva.deposito, reserva.inpag, reserva.acompanhante1, reserva.acompanhante2, reserva.acompanhante3, reserva.acompanhante4, reserva.mot_viagem, reserva.meio_transp, reserva.conhe_pousada, reserva.forma_in, cliente.nome  from reserva, cliente, conhe_pousada, meio_transp, mot_viagem where codigo = ? and reserva.cpf = cliente.cpf and reserva.mot_viagem = mot_viagem.cod_mv and reserva.meio_transp = meio_transp.cod_mt and reserva.conhe_pousada = conhe_pousada.cod_cp");
            comando.setString(1, codigo);
            ResultSet resultado = comando.executeQuery();
            if (resultado != null && resultado.next()) {
                txtNome.setText(resultado.getString("nome"));
                txtDataCheckIn.setText(resultado.getString("check_in"));
                txtDataCheckOut.setText(resultado.getString("check_out"));
                txtCarro.setText(resultado.getString("placa_carro"));
                txtReserva.setText(String.valueOf("R$" + resultado.getDouble("reserva")));
                txtDeposito.setText(String.valueOf("R$" + resultado.getDouble("deposito")));
                in.setText(String.valueOf("R$" + resultado.getDouble("inpag")));
                txtAc1.setText(resultado.getString("acompanhante1"));
                txtAc2.setText(resultado.getString("acompanhante2"));
                txtAc3.setText(resultado.getString("acompanhante3"));
                txtAc4.setText(resultado.getString("acompanhante4"));
                cbNq.setSelectedItem(resultado.getString("cod_quarto"));

                if(resultado.getString("forma_in").equals("Dinheiro")){
                    rbDinheiro.setSelected(true);
                }else if(resultado.getString("forma_in").equals("Cartão de Débito"))
                {
                    rbCartaoDebito.setSelected(true);
                }else if(resultado.getString("forma_in").equals("Transferência Bancária"))
                {
                    rbTransfBanc.setSelected(true);
                }
            }
            PreparedStatement comando2 = conexao.prepareStatement("Select mot_viagem.cod_mv, mot_viagem.mot_viagem from mot_viagem, reserva where reserva.mot_viagem = mot_viagem.cod_mv and codigo = ?");
            comando2.setString(1, codigo);
            ResultSet resultado2 = comando2.executeQuery();
            if (resultado2 != null && resultado2.next()) {
                cbMv.setSelectedItem(resultado2.getString("mot_viagem"));
            }
            
            PreparedStatement comando3 = conexao.prepareStatement("Select meio_transp.cod_mt, meio_transp.meio_transp from meio_transp, reserva where reserva.meio_transp = meio_transp.cod_mt and codigo = ?");
            comando3.setString(1, codigo);
            ResultSet resultado3 = comando3.executeQuery();
            if (resultado3 != null && resultado3.next()) {
                cbMt.setSelectedItem(resultado3.getString("meio_transp"));
            }
            
            PreparedStatement comando4 = conexao.prepareStatement("Select conhe_pousada.cod_cp, conhe_pousada.conhe_pousada from conhe_pousada, reserva where reserva.conhe_pousada = conhe_pousada.cod_cp and codigo = ?");
            comando4.setString(1, codigo);
            ResultSet resultado4 = comando4.executeQuery();
            if (resultado4 != null && resultado4.next()) {
                cbCp.setSelectedItem(resultado4.getString("conhe_pousada"));
            }
            
            resultado.close();
            resultado2.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados."+ex, "Erro!!!", 2);
        }
    }//GEN-LAST:event_tabCliMouseClicked

    private void txtAc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAc1ActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";

            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = null;
            if(compara==1){
                comando = conexao.prepareStatement("SELECT DATE_FORMAT(reserva.check_in, \"%d/%m/%Y\") as check_in, reserva.codigo, cliente.nome, cliente.cpf FROM reserva, cliente WHERE nome like ? and reserva.cpf = cliente.cpf order by nome");
                comando.setString(1, txtPesquisa.getText() + "%");
            } 
            if(compara==2){
                DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
                LocalDate checkin = LocalDate.parse(txtPesquisa.getText(), formato);
                comando = conexao.prepareStatement("SELECT DATE_FORMAT(reserva.check_in, \"%d/%m/%Y\") as check_in, reserva.codigo, cliente.nome, cliente.cpf FROM reserva, cliente WHERE reserva.check_in like ? and reserva.cpf = cliente.cpf order by check_in");
                comando.setDate(1, java.sql.Date.valueOf(checkin));
            }
            if(compara==3){
                comando = conexao.prepareStatement("SELECT DATE_FORMAT(reserva.check_in, \"%d/%m/%Y\") as check_in, reserva.codigo, cliente.nome, cliente.cpf FROM reserva, cliente WHERE cliente.cpf like ? and reserva.cpf = cliente.cpf order by nome");
                comando.setString(1, txtPesquisa.getText() + "%");
            }

            ResultSet resultado = comando.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tabCli.getModel();
            model.setNumRows(0);
            while (resultado.next()) {
                model.addRow(new Object[]{resultado.getString("codigo"), resultado.getString("check_in"), resultado.getString("nome"), resultado.getString("cliente.cpf"),});
            }
            resultado.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados." + ex, "Erro!!!", 2);
        }   
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void txtPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaKeyTyped

    private void txtDepositoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositoFocusLost
        in.setText(String.valueOf(Double.parseDouble(txtReserva.getText())-Double.parseDouble(txtDeposito.getText())));
    }//GEN-LAST:event_txtDepositoFocusLost

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        lTexto.setText("Digite o CPF do hóspede: ");
        compara=3;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        lTexto.setText("Digite o nome do hóspede: ");
        compara = 1;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void cbCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCpActionPerformed

    private void txtAc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAc4ActionPerformed

    private void cbMvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMvActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";
       
            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = conexao.prepareStatement("Select * from quarto order by num_quarto");
            ResultSet resultado = comando.executeQuery();
            while (resultado.next()) {
                cbNq.addItem(resultado.getString("num_quarto"));    
            }
            resultado.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados.", "Erro!!!", 2);
        }
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";
       
            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = conexao.prepareStatement("Select * from mot_viagem order by cod_mv");
            ResultSet resultado = comando.executeQuery();
            while (resultado.next()) {
                cbMv.addItem(resultado.getString("mot_viagem"));    
            }
            resultado.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados.", "Erro!!!", 2);
        }
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";
       
            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = conexao.prepareStatement("Select * from meio_transp order by cod_mt");
            ResultSet resultado = comando.executeQuery();
            while (resultado.next()) {
                cbMt.addItem(resultado.getString("meio_transp"));    
            }
            resultado.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados.", "Erro!!!", 2);
        }
        try {
            final String BANCO = "jdbc:mysql://localhost/pousada";
            final String USUARIO = "root";
            final String SENHA = "";
       
            Connection conexao = DriverManager.getConnection(BANCO, USUARIO, SENHA);
            PreparedStatement comando = conexao.prepareStatement("Select * from conhe_pousada order by cod_cp");
            ResultSet resultado = comando.executeQuery();
            while (resultado.next()) {
                cbCp.addItem(resultado.getString("conhe_pousada"));    
            }
            resultado.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Verifique a conexão com o banco de dados.", "Erro!!!", 2);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        lTexto.setText("Digite a data de check-in: ");
        compara=2;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarReserva1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCp;
    private javax.swing.JComboBox<String> cbMt;
    private javax.swing.JComboBox<String> cbMv;
    private javax.swing.JComboBox<String> cbNq;
    private javax.swing.JTextPane in;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTexto;
    private javax.swing.JRadioButton rbCartaoDebito;
    private javax.swing.JRadioButton rbDinheiro;
    private javax.swing.JRadioButton rbTransfBanc;
    private javax.swing.JTable tabCli;
    private javax.swing.JTextField txtAc1;
    private javax.swing.JTextField txtAc2;
    private javax.swing.JTextField txtAc3;
    private javax.swing.JTextField txtAc4;
    private javax.swing.JTextField txtCarro;
    private javax.swing.JFormattedTextField txtDataCheckIn;
    private javax.swing.JFormattedTextField txtDataCheckOut;
    private javax.swing.JTextField txtDeposito;
    private javax.swing.JTextPane txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtReserva;
    // End of variables declaration//GEN-END:variables
}
